=== danilocavallini01/PAW/ESAMI/2021Giu18_1/resources/18Giu2021.xsd
<?xml version="1.0" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:complexType name="RistoranteType">
		<xs:sequence>
			<xs:element name="nome" type="xs:string" />
			<xs:element name="localita" type="xs:string" />
			<xs:element name="indirizzo" type="IndirizzoType" />
			<xs:element name="telefono" type="TelefonoType" />
			<xs:element name="link" type="xs:string" minOccurs="0" />
			
			<xs:element name="antipasti" type="CategoriaType" />
			<xs:element name="primi" type="CategoriaType" />
			<xs:element name="secondi" type="CategoriaType" />
			<xs:element name="contorni" type="CategoriaType" />
			<xs:element name="dessert" type="CategoriaType" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="IndirizzoType">
		<xs:sequence>
			<xs:element name="via" type="xs:string" />
			<xs:element name="numeroCivico" type="xs:integer" />
			<xs:element name="CAP" type="xs:integer" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="TelefonoType">
		<xs:sequence>
			<xs:element name="prefisso" type="xs:string" />
			<xs:element name="numero" type="xs:integer" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="CategoriaType">
		<xs:sequence>
			<xs:element name="piatto" type="PiattoType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="PiattoType">
		<xs:sequence>
			<xs:element name="nome" type="xs:string" />
			<xs:element name="prezzo" type="xs:float" />
		</xs:sequence>
	</xs:complexType>

	<xs:element name="ristorante" type="RistoranteType" />
</xs:schema>

=== danilocavallini01/PAW/ESAMI/2021Giu18_1/resources/18Giu2021.xml
<?xml version="1.0" encoding="UTF-8"?>
<ristorante
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="18Giu2021.xsd">
	<nome>nome</nome>
	<localita>localita</localita>
	<indirizzo>
		<via>via</via>
		<numeroCivico>0</numeroCivico>
		<CAP>0</CAP>
	</indirizzo>
	<telefono>
		<prefisso>prefisso</prefisso>
		<numero>0</numero>
	</telefono>
	<link>link</link>
	<antipasti>
		<piatto>
			<nome>nome</nome>
			<prezzo>0.0</prezzo>
		</piatto>
	</antipasti>
	<primi>
		<piatto>
			<nome>nome</nome>
			<prezzo>0.0</prezzo>
		</piatto>
		<piatto>
			<nome>nome</nome>
			<prezzo>0.0</prezzo>
		</piatto>
		<piatto>
			<nome>nome</nome>
			<prezzo>0.0</prezzo>
		</piatto>
	</primi>
	<secondi>
		<piatto>
			<nome>nome</nome>
			<prezzo>0.0</prezzo>
		</piatto>
	</secondi>
	<contorni>
		<piatto>
			<nome>nome</nome>
			<prezzo>0.0</prezzo>
		</piatto>
	</contorni>
	<dessert>
		<piatto>
			<nome>nome</nome>
			<prezzo>0.0</prezzo>
		</piatto>
	</dessert>
</ristorante>
