=== danilocavallini01/PAW/ESAMI/16Giu2022_1/resources/16giu2022.xsd
<?xml version="1.0" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:complexType name="BibliotecaType">
		<xs:sequence>
			<xs:element name="musicista" type="MusicistaType" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="MusicistaType">
		<xs:sequence>
			<xs:element name="nome" type="xs:string" />
			<xs:element name="cognome" type="xs:string" />
			<xs:element name="nomeArte" type="xs:string" minOccurs="0" />
			<xs:element name="genere" type="xs:string" />
			<xs:element name="album" type="AlbumType" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="AlbumType">
		<xs:sequence>
			<xs:element name="titoloAlbum" type="xs:string" />
			<xs:element name="annoPubblicazione" type="xs:positiveInteger" />
			<xs:element name="brano" type="BranoType" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="BranoType">
		<xs:sequence>
			<xs:element name="titoloBrano" type="xs:string" />
			<xs:element name="lunghezza">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[0-9][0-9]:[0-9][0-9]" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:element name="bibliotecaMusicale" type="BibliotecaType" />
</xs:schema>

=== danilocavallini01/PAW/ESAMI/2022Giu16_1/resources/16giu2022.xml
<?xml version="1.0" encoding="UTF-8"?>
<bibliotecaMusicale
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="16giu2022.xsd">
	<musicista>
		<nome>van gogh</nome>
		<cognome>cognome</cognome>
		<nomeArte>nomeArte</nomeArte>
		<genere>genere</genere>
		<album>
			<titoloAlbum>titoloAlbum</titoloAlbum>
			<annoPubblicazione>1</annoPubblicazione>
			<brano>
				<titoloBrano>Bro</titoloBrano>
				<lunghezza>02:02</lunghezza>
			</brano>
		</album>
	</musicista>
</bibliotecaMusicale>
